version: '3'

services:
  db:
    image: postgres:latest
    container_name: database
    ports:
      - 5433:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    image: hari6091/retronatus-api:latest
    container_name: backend
    ports:
      - 5000:5000
    command: sh -c "git pull origin main && npm i && npm run dev"
    depends_on:
      - db
    networks:
      - my_network

  frontend:
    image: hari6091/retronatus_frontend:latest
    container_name: frontend
    ports:
      - 3000:3000
    command: sh -c "git pull origin main && npm i && npm start"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:


volumes:
  pg-data:
